name: radiokit_widgets_example
description: Widget Playground for RadioKit.
publish_to: none
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  radiokit_widgets:
    path: ../
  go_router: ^14.0.0
  lucide_icons_flutter: ^3.1.13
  simple_icons:
    git:
      url: https://github.com/PiscesXD/simple_icons.git
      ref: master
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
